#------LICENSE--------
#MIT License
#
#Copyright (c) 2020 AICPA

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

openapi: 3.0.0
info:
  version: "1.0.0"
  title: Audit Data Open Api Project (AICPA) - Accounts Receivable Module
  description: This is an initial API specification for requesting Inventory data 

paths:
  /InventoryOnHand:
    get:
      operationId: GetInventoryOnHand
      tags: [Inventory]      
      description: >
        Captures the on-hand inventory quantities of items by location and amounts as of the specified date.

        Should be able to pass a date and get back a list of all inventory on hand at that date.
      parameters:
        - name: balanceDate
          in: query
          description: Inventory on hand on a given date. 
          required: true
          schema:
            type: string

        - $ref: '../shared/parameters/index.yml#/entityIdRequiredParam'
      
      responses:
        '200':
          description: __GetInventoryOnHand__ successfully accepted
          content:  
            application/json:
              schema:
                $ref: './schemas/index.yml#/InventoryOnHandItems'
        '400':
          $ref: '../shared/responses/index.yml#/BadRequest'

  /InventoryTransactions:
    get:
      operationId: GetInventoryTransactions
      tags: [Inventory]      
      description: >
        Captures all transaction history (for example, receipts, shipments, transfers, returns, adjustments) affecting inventory accounts during the time period specified.

        Should be able to pass a start and end date and get back a list of all transactions during the period.
      parameters:
        - name: startDate
          in: query
          description: Returns all invoices with a start date equal or greater than the start date.
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: Returns all invoices with an end date equal or less than the end date.
          required: true
          schema:
            type: string
            format: date
        - $ref: '../shared/parameters/index.yml#/entityIdRequiredParam'
      
      responses:
        '200':
          description: __GetInventoryTransactions__ successfully accepted
          content:  
            application/json:
              schema:
                $ref: './schemas/index.yml#/InventoryTransactionItems'
        '400':
          $ref: '../shared/responses/index.yml#/BadRequest'