#------LICENSE--------
#MIT License
#
#Copyright (c) 2020 AICPA

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

openapi: 3.0.0
info:
  version: "1.0.0"
  title: Audit Data Open Api Project (AICPA) - Accounts Payable Module
  description: This is an initial API specification for requesting AP data 

paths:
  /OpenBalances:
    get:
      operationId: GetAPOpenAccountsPayable
      tags: [Accounts Payable]      
      description: >

        Each record represents the balance due to the supplier for one uniquely identifiable transaction. This file should be at the summary level (by
        invoice), not at the detailed level (by invoice line item). The sum total of the transaction amounts as of the specified date should reconcile to the total AP amount in the general ledger (GL) as of the same date. 

        Should be able to pass a date and get back a list of all the invoices amounts that were outstanding at that date.
      parameters:
        - name: balanceDate
          in: query
          description: Open payables on a given date. 
          required: true
          schema:
            type: string

        - $ref: '../shared/parameters/index.yml#/entityIdRequiredParam'
      
      responses:
        '200':
          description: __GetAPOpenAccountsPayables__ successfully accepted
          content:  
            application/json:
              schema:
                $ref: './schemas/index.yml#/APOpenAccountsPayableItems'
        '400':
          $ref: '../shared/responses/index.yml#/BadRequest'

  /Suppliers:
    get:
      operationId: GetAPSuppliers
      tags: [Accounts Payable]      
      description: >
        Allows the retrieval of the supplier listing for the entity. Supplier information can be requested based on a supplier ID. 
      parameters:
        - $ref: '../shared/parameters/index.yml#/supplierAccountIDParam'
        - $ref: '../shared/parameters/index.yml#/entityIdRequiredParam'
      
      responses:
        '200':
          description: __GetAPSuppliers__ successfully accepted
          content:  
            application/json:
              schema:
                $ref: '../Entities/schemas/index.yml#/Suppliers'
        '400':
          $ref: '../shared/responses/index.yml#/BadRequest'

  /Invoices:
    get:
      operationId: GetAPInvoices
      tags: [Accounts Payable]      
      description: >
        Invoices has one record for each purchase order associated with each invoice. For example, if an invoice includes items from three purchase orders, there will be three records for that one invoice. The invoice will include the associated three purchase orders.
      parameters:
        - $ref: '../shared/parameters/index.yml#/supplierAccountIDParam'
        - name: startDate
          in: query
          description: Returns all invoices with a start date equal or greater than the start date.
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: Returns all invoices with an end date equal or less than the end date.
          required: true
          schema:
            type: string
            format: date
        - $ref: '../shared/parameters/index.yml#/entityIdRequiredParam'
      
      responses:
        '200':
          description: __GetAPInvoices__ successfully accepted
          content:  
            application/json:
              schema:
                $ref: './schemas/index.yml#/APInvoices'
        '400':
          $ref: '../shared/responses/index.yml#/BadRequest'
  
  /PaymentsMade:
    get:
      operationId: GetPaymentsMade
      tags: [Accounts Payable]      
      description: >
        The payments made contains all payment transactions (check, wire transfer, cash, and so on) made during the period. Each record represents a single cash receipt.
      parameters:
        - $ref: '../shared/parameters/index.yml#/supplierAccountIDParam'
        - name: startDate
          in: query
          description: Returns all payments with a start date equal or greater than the start date.
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: Returns all payments with an end date equal or less than the end date.
          required: true
          schema:
            type: string
            format: date
        - $ref: '../shared/parameters/index.yml#/entityIdRequiredParam'
      
      responses:
        '200':
          description: __GetPaymentsMade__ successfully accepted
          content:  
            application/json:
              schema:
                $ref: './schemas/index.yml#/APPaymentsMade'
        '400':
          $ref: '../shared/responses/index.yml#/BadRequest'