name: Build & Publish JS Packages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        #  git branch --remote --contains | grep origin/master      
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Extract release notes
        run: |
          git log --no-walk --tags --pretty=format:"%d %s" | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' >> RELEASE-NOTES.md
      - name: Clone Build Scripts
        run: |
          git clone --no-tags --depth=1 https://github.com/AICPA-ADS/AuditData-API-Packages.git ./_scripts
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: |
          pushd ./_scripts
          bash generate-model.sh ts ../ ${VERSION} /tmp/ads-build/
          bash generate-client.sh ts ../ ${VERSION} /tmp/ads-build/
          popd 
      - name: Push
        run: |
            npm publish ./_scripts/dist/js/aicpa-ads-auditdata-model-${VERSION}.tgz --access public
            npm publish ./_scripts/dist/js/aicpa-ads-auditdata-client-${VERSION}.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}      